### ISSUE TITLE
AssertionError,This error occurred when I labeling

### ISSUE THREAD

**Issue by sisyphus229** [open-mmlab/playground#117]
[ERROR] [label_studio_ml.model::get_result_from_last_job::131] 1685446124 job returns exception:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/wyz-labelsam/lib/python3.9/site-packages/label_studio_ml/model.py", line 129, in get_result_from_last_job
    result = self.get_result_from_job_id(job_id)
  File "/home/ubuntu/anaconda3/envs/wyz-labelsam/lib/python3.9/site-packages/label_studio_ml/model.py", line 111, in get_result_from_job_id
    assert isinstance(result, dict)
AssertionError
When I'm labeling, there's a lag. On the backend, you also get the above error message.

**Comment by JimmyMa99** [comment]
This looks like an error that occurred in LS backend reasoning, you can look at the issues in LS specifically, hope this link can help you.
[https://github.com/heartexlabs/label-studio/issues/2850](url)

**Comment by sisyphus229** [comment]
> This looks like an error that occurred in LS backend reasoning, you can look at the issues in LS specifically, hope this link can help you. [https://github.com/heartexlabs/label-studio/issues/2850](url)

Hello, please give me a valid link, this url is broken.

**Comment by pinecho** [comment]
Hi, I have encountered the same problem. Have anyone fixed this?
