### ISSUE TITLE
 export: coco, xml not happening the following error keeps popping

### ISSUE THREAD

**Issue by paineni** [open-mmlab/playground#123]
Traceback (most recent call last):
  File "/home/paineni/micromamba/envs/detectron_env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/paineni/micromamba/envs/detectron_env/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/paineni/micromamba/envs/detectron_env/lib/python3.8/site-packages/label_studio/data_export/api.py", line 183, in get
    export_stream, content_type, filename = DataExport.generate_export_file(
  File "/home/paineni/micromamba/envs/detectron_env/lib/python3.8/site-packages/label_studio/data_export/models.py", line 161, in generate_export_file
    converter.convert(input_json, tmp_dir, output_format, is_dir=False)
  File "/home/paineni/micromamba/envs/detectron_env/lib/python3.8/site-packages/label_studio_converter/converter.py", line 209, in convert
    self.convert_to_coco(
  File "/home/paineni/micromamba/envs/detectron_env/lib/python3.8/site-packages/label_studio_converter/converter.py", line 679, in convert_to_coco
    x, y, w, h = self.rotated_rectangle(label)
  File "/home/paineni/micromamba/envs/detectron_env/lib/python3.8/site-packages/label_studio_converter/converter.py", line 916, in rotated_rectangle
    label["x"],
KeyError: 'x'

**Comment by paineni** [comment]
required a solution as soon as possible

**Comment by JimmyMa99** [comment]
Sorry for the late reply, I've been a bit busy lately. The reason for this error may be that the conversion failed due to your markup not being completed.

**Comment by xji-apex** [comment]
same error,how to solve it？？？、

**Comment by JimmyMa99** [comment]
Is it because of a problem with the configuration environment?
Here is a video explaining the configuration environment: [https://www.bilibili.com/video/BV1hh411F7uR/](url)

**Comment by paineni** [comment]
Thanks that helps a lot

**Comment by khadija23** [comment]
I'm faced same issue but link @JimmyMa99  suggest does't work, can you please tell me how you solve @vansin
