### ISSUE TITLE
label_anything: RuntimeError: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by lyg2021** [open-mmlab/playground#130]
I'm getting an error like this that doesn't work when I use label_anything

Traceback (most recent call last):
  File "/home/qlab3090/.conda/envs/rtmdet-sam/lib/python3.9/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/home/qlab3090/.conda/envs/rtmdet-sam/lib/python3.9/site-packages/label_studio_ml/api.py", line 51, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "/home/qlab3090/.conda/envs/rtmdet-sam/lib/python3.9/site-packages/label_studio_ml/model.py", line 617, in predict
    predictions = cls._current_model.model.predict(tasks, **kwargs)
  File "/home/qlab3090/dataDepot2T/Workplace/lyg/python/playground/label_anything/sam/mmdetection.py", line 173, in predict
    predictor.set_image(image)
  File "/home/qlab3090/.conda/envs/rtmdet-sam/lib/python3.9/site-packages/segment_anything/predictor.py", line 60, in set_image
    self.set_torch_image(input_image_torch, image.shape[:2])
  File "/home/qlab3090/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/qlab3090/.conda/envs/rtmdet-sam/lib/python3.9/site-packages/segment_anything/predictor.py", line 89, in set_torch_image
    self.features = self.model.image_encoder(input_image)
  File "/home/qlab3090/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/qlab3090/.conda/envs/rtmdet-sam/lib/python3.9/site-packages/segment_anything/modeling/image_encoder.py", line 107, in forward
    x = self.patch_embed(x)
  File "/home/qlab3090/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/qlab3090/.conda/envs/rtmdet-sam/lib/python3.9/site-packages/segment_anything/modeling/image_encoder.py", line 392, in forward
    x = self.proj(x)
  File "/home/qlab3090/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/qlab3090/.local/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/qlab3090/.local/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation

**Comment by JimmyMa99** [comment]
Check dependencies: Make sure that all dependencies in your environment are installed correctly and are version compatible. In particular, check the versions of label_studio_ml, segment_anything and related libraries. You can try to update these libraries to ensure that you are using the latest stable version.

Check the model configuration: Check the model configuration file you are using when using label_anything. Make sure that the configuration file is set up correctly and that all required parameters and paths are specified correctly.

Check the calculation engine: Depending on the hint in the error message, the calculation could not be executed due to a problem with the calculation engine. Make sure that the computation engine in your computing environment is properly configured and compatible with the libraries used. If necessary, try switching or updating the calculation engine.

Ask for help: If none of the above methods solve the problem, it is recommended that you ask for help from label_anything or the developer community of the library in question. They may be able to provide a more specific solution or guide you through troubleshooting.

**Comment by lyg2021** [comment]
Thanks for your reply, I have successfully run the program by using the cpu version.
