### ISSUE TITLE
KeyError: 'KeyPointLabels'

### ISSUE THREAD

**Issue by nuistZPZ** [open-mmlab/playground#131]
代码中获取前端参数的语句如下
![image](https://github.com/open-mmlab/playground/assets/103711400/e5503dc4-efa1-4b09-90f1-d2cf1d9fc433)

但是实际上前端返回的JSON参数中没有 KeyPointLabels，而是根据选择任务的不同会有不同的返回值，比如选择用关键点来标注语义分割，返回值就是 Label:{}，如下所示。使用掩膜来标注，返回值就是 Tag:{}
![image](https://github.com/open-mmlab/playground/assets/103711400/1bcf4783-4368-4fe6-be7e-78118499e74c)

**Comment by nuistZPZ** [comment]
完整报错如下，
Traceback (most recent call last):
  File "D:\Anaconda\Anacoda3-2022.05\envs\pytorch\lib\site-packages\label_studio_ml\exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "D:\Anaconda\Anacoda3-2022.05\envs\pytorch\lib\site-packages\label_studio_ml\api.py", line 70, in _setup
    model = _manager.fetch(project, schema, force_reload,
  File "D:\Anaconda\Anacoda3-2022.05\envs\pytorch\lib\site-packages\label_studio_ml\model.py", line 535, in fetch
    model = cls.model_class(label_config=label_config, train_output=job_result, **kwargs)
  File "D:\WorkDocument\Project\Pytorch\segment\playground\label_anything\sam\mmdetection.py", line 84, in __init__
    label=self.parsed_label_config['KeyPointLabels']
KeyError: 'KeyPointLabels'

**Comment by nuistZPZ** [comment]
使用的label-studio==1.7.3，使用的label-studio-ml==1.0.9。
其余配置参考这篇博客https://mp.weixin.qq.com/s/02150wGJngAr_bZKNZUJLw

**Comment by nuistZPZ** [comment]
【已解决】可以参考https://www.bilibili.com/video/BV1TP41117ai/ 跟着配置
【错误原因】最后一步没有输入openmmlab设置好的xml，而是选择了label-studio的模板
下面是正确做法
![image](https://github.com/open-mmlab/playground/assets/103711400/b75c8987-a273-46ed-97fb-64963f92a58b)
下面是错误做法，不应该点击模板来配置XML
![image](https://github.com/open-mmlab/playground/assets/103711400/02e98a7a-3b95-427c-be3d-0e3a45b44831)

**Comment by chenaa232** [comment]
good!!!
