### ISSUE TITLE
The GroundingDINO section encountered an error

### ISSUE THREAD

**Issue by Vio1etovo** [open-mmlab/playground#155]
My environment configuration is as follows:
```
ubuntu18.04.6-torch1.9-py3.8-cuda11.1-gpu
```

The first two commands ran normally, while the third (using GroundingDINO) ran incorrectly. The error is as follows:

```
root@vscode-1690977852929548290-8588864677-qfmcx:/work/home/sam/playground-main/playground-main/mmdet_sam# python detector_sam_demo.py ../images/cat_remote.jpg \
>     configs/GroundingDINO_SwinT_OGC.py \
>     ../models/groundingdino_swint_ogc.pth \
>     -t "cat . remote" \
>     --sam-device cpu
final text_encoder_type: bert-base-uncased
Traceback (most recent call last):
  File "detector_sam_demo.py", line 529, in <module>
    main()
  File "detector_sam_demo.py", line 450, in main
    det_model = build_detecter(args)
  File "detector_sam_demo.py", line 168, in build_detecter
    detecter = __build_grounding_dino_model(args)
  File "detector_sam_demo.py", line 124, in __build_grounding_dino_model
    model = build_model(gdino_args)
  File "/work/home/sam/playground-main/GroundingDINO/groundingdino/models/__init__.py", line 17, in build_model
    model = build_func(args)
  File "/work/home/sam/playground-main/GroundingDINO/groundingdino/models/GroundingDINO/groundingdino.py", line 388, in build_groundingdino
    model = GroundingDINO(
  File "/work/home/sam/playground-main/GroundingDINO/groundingdino/models/GroundingDINO/groundingdino.py", line 108, in __init__
    self.bert = get_tokenlizer.get_pretrained_language_model(text_encoder_type)
  File "/work/home/sam/playground-main/GroundingDINO/groundingdino/util/get_tokenlizer.py", line 25, in get_pretrained_language_model
    return BertModel.from_pretrained(text_encoder_type)
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 2805, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 469, in load_state_dict
    return safe_load_file(checkpoint_file)
  File "/usr/local/lib/python3.8/dist-packages/safetensors/torch.py", line 310, in load_file
    result[k] = f.get_tensor(k)
AttributeError: module 'torch' has no attribute 'frombuffer'
```

I found in the official` torch 1.9.0` document that `torch.frombuffer` does not exist, and `torch 2.0.0` does.

Is it necessary to upgrade to `torch 2.0.0`

**Comment by Vio1etovo** [comment]
See [Here](https://github.com/huggingface/transformers/issues/25847)

Huggingface's safesensors no longer support versions below `torch 1.10.0`
