### ISSUE TITLE
我在linux服务器上面搭建服务器，在自己本地的windows上面建立客户端，但是模型推理的·时候·出现下面·报错·

### ISSUE THREAD

**Issue by MMa321** [open-mmlab/playground#170]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /data/upload/3/1381ce70-IMG_20210627_225110.jpg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f178c0a27f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

[2024-02-02 11:19:07,096] [INFO] [werkzeug::_log::225] 192.168.1.225 - - [02/Feb/2024 11:19:07] "POST /predict HTTP/1.1" 500 -

**Comment by RavenMuse** [comment]
@MMa321 Hi there , you could add hostname to the parameters to help bankend find
pictures where uploaded in LabelStudio , like this

label-studio-ml start sam --port 9500 --with \
  sam_config=vit_b \
  hostname= http://hostname:port \
  sam_checkpoint_file=./sam_vit_b_01ec64.pth \
  out_mask=True \
  out_bbox=True \
  device=cuda:0

**Comment by MMa321** [comment]
Thank you for your answer, it was useful

**Comment by wdc233** [comment]
> Thank you for your answer, it was useful

请问具体是怎样的命令呢？我加了hostname:http://localhost:8080
但是没用

**Comment by MMa321** [comment]
If the server and the client is not a machine, you need the hostname of the hostname = http://hostname:port, such as the hostname = http://192.168.1.100:8080

**Comment by MMa321** [comment]
> > Thank you for your answer, it was useful
> 
> 请问具体是怎样的命令呢？我加了hostname:http://localhost:8080 但是没用

If the server and the client is not a machine, you need the hostname of the hostname = http://hostname:port, such as the hostname = http://192.168.1.100:8080

**Comment by cocoz150** [comment]
my parameters are like :
label-studio-ml start sam --port 9500 --with
sam_config=vit_b
hostname= http://hostname:port/  (the hostname is the same as my server's ip)
sam_checkpoint_file=./sam_vit_b_01ec64.pth
out_mask=True
out_bbox=True
device=cuda:0
But the traceback is like:
Traceback (most recent call last):
  File "/data/HHH/Projects/playground-main/playground-main/label_anything/./sam/_wsgi.py", line 121, in <module>
    kwargs.update(parse_kwargs())
  File "/data/HHH/Projects/playground-main/playground-main/label_anything/./sam/_wsgi.py", line 105, in parse_kwargs
    for k, v in args.kwargs:
ValueError: not enough values to unpack (expected 2, got 1)
How could i solve this traceback?please 😭
