### ISSUE TITLE
导出coco格式报错，我需要导出out_poly，在标注的过程中一开始是没问题的，有多边形和brush，标注有自动的，也有手动的，后面不知道为什么报错。

### ISSUE THREAD

**Issue by cabbage404** [open-mmlab/playground#177]
Traceback (most recent call last):
  File "D:\mysoftware\anaconda\envs\rtmdet-sam\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\mysoftware\anaconda\envs\rtmdet-sam\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\mysoftware\anaconda\envs\rtmdet-sam\lib\site-packages\label_studio\data_export\api.py", line 183, in get
    export_stream, content_type, filename = DataExport.generate_export_file(
  File "D:\mysoftware\anaconda\envs\rtmdet-sam\lib\site-packages\label_studio\data_export\models.py", line 161, in generate_export_file
    converter.convert(input_json, tmp_dir, output_format, is_dir=False)
  File "D:\mysoftware\anaconda\envs\rtmdet-sam\lib\site-packages\label_studio_converter\converter.py", line 209, in convert
    self.convert_to_coco(
  File "D:\mysoftware\anaconda\envs\rtmdet-sam\lib\site-packages\label_studio_converter\converter.py", line 679, in convert_to_coco
    x, y, w, h = self.rotated_rectangle(label)
  File "D:\mysoftware\anaconda\envs\rtmdet-sam\lib\site-packages\label_studio_converter\converter.py", line 916, in rotated_rectangle
    label["x"],
KeyError: 'x'

**Comment by cabbage404** [comment]
报错的时候能不能输出是哪张图片报错了，或者导出的时候能不能只选一部分导出，找不到好痛苦
