### ISSUE TITLE
Export data error

### ISSUE THREAD

**Issue by TonyMacedonia** [open-mmlab/playground#84]
When I select the COCO format to export, the following error occurs.

Traceback (most recent call last):
  File "F:\Anaconda\anaconda\envs\rtmdet-sam\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\Anaconda\anaconda\envs\rtmdet-sam\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "F:\Anaconda\anaconda\envs\rtmdet-sam\lib\site-packages\label_studio\data_export\api.py", line 183, in get
    export_stream, content_type, filename = DataExport.generate_export_file(
  File "F:\Anaconda\anaconda\envs\rtmdet-sam\lib\site-packages\label_studio\data_export\models.py", line 161, in generate_export_file
    converter.convert(input_json, tmp_dir, output_format, is_dir=False)
  File "F:\Anaconda\anaconda\envs\rtmdet-sam\lib\site-packages\label_studio_converter\converter.py", line 209, in convert
    self.convert_to_coco(
  File "F:\Anaconda\anaconda\envs\rtmdet-sam\lib\site-packages\label_studio_converter\converter.py", line 700, in convert_to_coco
    (x / 100 * width, y / 100 * height) for x, y in label["points"]
KeyError: 'points'

**Comment by JimmyMa99** [comment]
Maybe you need to check your xml configuration.
```
<View>
  <Image name="image" value="$image" zoom="true"/>
  <KeyPointLabels name="KeyPointLabels" toName="image">
    <Label value="cat" smart="true" background="#e51515" showInline="true"/>
    <Label value="person" smart="true" background="#412cdd" showInline="true"/>
  </KeyPointLabels>
  <RectangleLabels name="RectangleLabels" toName="image">
  	<Label value="cat" background="#FF0000"/>
  	<Label value="person" background="#0d14d3"/>
  </RectangleLabels>
  <PolygonLabels name="PolygonLabels" toName="image">
  	<Label value="cat" background="#FF0000"/>
  	<Label value="person" background="#0d14d3"/>
  </PolygonLabels>
  <BrushLabels name="BrushLabels" toName="image">
  	<Label value="cat" background="#FF0000"/>
  	<Label value="person" background="#0d14d3"/>
  </BrushLabels>
</View>
```

**Comment by jianzhangru** [comment]
I got the same error. I don't see much difference between my XML and your example configuration.

**Comment by JimmyMa99** [comment]
Can you provide the xml for inspection?

**Comment by jianzhangru** [comment]
Sure.

<View>
  <Image name="image" value="$image" zoom="true"/>
  <KeyPointLabels name="KeyPointLabels" toName="image">
    <Label value="object" smart="true" background="red" showInline="true"/>
  </KeyPointLabels>
  <RectangleLabels name="RectangleLabels" toName="image">
  	<Label value="object" background="blue"/>
  </RectangleLabels>
  <PolygonLabels name="PolygonLabels" toName="image">
  	<Label value="object" background="green"/>
  </PolygonLabels>
  <BrushLabels name="BrushLabels" toName="image">
  	<Label value="object" background="#8F4000"/>
  </BrushLabels>
</View>
