### ISSUE TITLE
AttributeError:'MMDetection' object has no attribute 'value'

### ISSUE THREAD

**Issue by yi2xu** [open-mmlab/playground#97]
The page doesn't split automatically when I annotate the images

**Comment by luxiaoyan95** [comment]
I used my own jpg image, followed the same steps and also encountered this problem, anyone know why？

**Comment by JimmyMa99** [comment]
Which project is the error?

**Comment by JimmyMa99** [comment]
Can you provide more detailed information about the error report?

**Comment by zym3122** [comment]
> The page doesn't split automatically when I annotate the images

me too

**Comment by JimmyMa99** [comment]
> > The page doesn't split automatically when I annotate the images
> 
> me too

Can you provide more detailed information about the error report?
It may be an error in the back-end reasoning, please can you provide more detailed error reporting tips, such as screenshot back-end terminal

**Comment by chensjtu** [comment]
i get the same bug, it seems as if the load is wrong. 
<img width="1120" alt="image" src="https://github.com/open-mmlab/playground/assets/38242929/e0c53437-77a7-4447-9f82-53e6f5477b8f">
only BrushLabels has the attribute 'value', Traceback (most recent call last):
  File "/home/yangchen/.conda/envs/rtmdet-sam/lib/python3.9/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/home/yangchen/.conda/envs/rtmdet-sam/lib/python3.9/site-packages/label_studio_ml/api.py", line 51, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "/home/yangchen/.conda/envs/rtmdet-sam/lib/python3.9/site-packages/label_studio_ml/model.py", line 617, in predict
    predictions = cls._current_model.model.predict(tasks, **kwargs)
  File "/data_hdd2/users/yangchen/projects/playground/label_anything/sam/mmdetection.py", line 164, in predict
    image_url = self._get_image_url(task)
  File "/data_hdd2/users/yangchen/projects/playground/label_anything/sam/mmdetection.py", line 137, in _get_image_url
    self.value) or task['data'].get(DATA_UNDEFINED_NAME)
AttributeError: 'MMDetection' object has no attribute 'value'
